### ISSUE TITLE
execute() 方法语法错误时会报Call to a member function handle() on null 

### ISSUE THREAD

**Issue by hs-llsong** [inhere/php-console#11]
`execute($input, $output)`方法语法错误时会报`Call to a member function handle() on null `
原因是 `prepareRun` 里面setter`$this->errorHandler`没有调用到

```
Fatal error: Uncaught Error: Call to a member function handle() on null in /home/tester/vendor/inhere/console/src/Base/AbstractApplication.php:298
Stack trace:
#0 [internal function]: Inhere\Console\Base\AbstractApplication->handleException(Object(ParseError))
#1 {main}
  thrown in /home/tester/vendor/inhere/console/src/Base/AbstractApplication.php on line 298

Fatal error: Uncaught Error: Call to a member function handle() on null in /home/tester/vendor/inhere/console/src/Base/AbstractApplication.php:298
Stack trace:
#0 /home/tester/vendor/inhere/console/src/Base/AbstractApplication.php(285): Inhere\Console\Base\AbstractApplication->handleException(Object(ErrorException))
#1 /home/tester/vendor/inhere/console/src/Base/AbstractApplication.php(270): Inhere\Console\Base\AbstractApplication->handleError(1, 'Uncaught Error:...', '/home/sll/Proje...', 298)
#2 [internal function]: Inhere\Console\Base\AbstractApplication->Inhere\Console\Base\{closure}()
#3 {main}
  thrown in /home/tester/vendor/inhere/console/src/Base/AbstractApplication.php on line 298
```

**Comment by inhere** [comment]
@hs-llsong 你下载的版本是多少？之前的是有这个问题，没有提前设置错误处理类，后面的版本已经是修复了这个问题了

**Comment by hs-llsong** [comment]
版本信息：

```
# CHANGELOG

## v2.4.0

> publish at: 2018.07.03

- **update deps**: add dep toolkit/cli-utils and toolkit/sys-utils
- fix: no des when display alone command help
- add new interactive method: `Interact::answerIsYes()`
- update PharCompiler.php, some bug fixed
- adjust help information display
- remove some invalid classes
```

**Comment by inhere** [comment]
用的 v2 吗？ 我修复下

**Comment by inhere** [comment]
发了 `2.4.3`，你更新看一下

- 修复了错误处理类未提前设置的问题

https://github.com/inhere/php-console/commit/ba30f06c0ad3d26d9fc56debd6e46cc4a68adb81
